'use strict';

module.exports = [
  {
    id: 'living-room-ceiling',
    name: 'Living room ceiling',
    zoneCandidates: ['Living Room'],
    deviceClass: 'light',
    icon: '/icons/light.svg',
    capabilities: ['onoff', 'dim', 'light_temperature', 'measure_power'],
    initialState: { onoff: true, dim: 0.72, light_temperature: 0.38, measure_power: 9.4 },
  },
  {
    id: 'bedroom-fan',
    name: 'Bedroom fan',
    zoneCandidates: ['Bedroom', 'Master Bedroom'],
    deviceClass: 'fan',
    icon: '/icons/fan.svg',
    capabilities: ['onoff', 'dim', 'measure_power'],
    initialState: { onoff: true, dim: 0.4, measure_power: 18.2 },
  },
  {
    id: 'kitchen-coffee-maker',
    name: 'Coffee maker',
    zoneCandidates: ['Kitchen'],
    deviceClass: 'socket',
    icon: '/icons/socket.svg',
    capabilities: ['onoff', 'measure_power', 'meter_power', 'measure_voltage', 'measure_current'],
    initialState: {
      onoff: false,
      measure_power: 0,
      meter_power: 12.45,
      measure_voltage: 230.1,
      measure_current: 0,
    },
  },
  {
    id: 'living-room-climate',
    name: 'Living room climate',
    zoneCandidates: ['Living Room'],
    deviceClass: 'thermostat',
    icon: '/icons/thermostat.svg',
    capabilities: ['onoff', 'target_temperature', 'measure_temperature', 'measure_humidity'],
    capabilitiesOptions: {
      target_temperature: { min: 5, max: 35, step: 0.5 },
    },
    initialState: {
      onoff: true,
      target_temperature: 21.5,
      measure_temperature: 21.6,
      measure_humidity: 46,
    },
  },
  {
    id: 'hallway-multisensor',
    name: 'Hallway multisensor',
    zoneCandidates: ['Hallway', 'Entrance'],
    deviceClass: 'sensor',
    icon: '/icons/sensor.svg',
    capabilities: [
      'alarm_contact',
      'alarm_motion',
      'alarm_smoke',
      'alarm_water',
      'measure_temperature',
      'measure_humidity',
      'measure_co2',
      'measure_luminance',
      'measure_battery',
    ],
    initialState: {
      alarm_contact: false,
      alarm_motion: false,
      alarm_smoke: false,
      alarm_water: false,
      measure_temperature: 20.8,
      measure_humidity: 43,
      measure_co2: 590,
      measure_luminance: 120,
      measure_battery: 87,
    },
  },
  {
    id: 'front-door-lock',
    name: 'Front door lock',
    zoneCandidates: ['Hallway', 'Entrance'],
    deviceClass: 'lock',
    icon: '/icons/lock.svg',
    capabilities: ['locked', 'alarm_contact', 'measure_battery'],
    initialState: { locked: true, alarm_contact: false, measure_battery: 78 },
  },
  {
    id: 'bedroom-blind',
    name: 'Bedroom blind',
    zoneCandidates: ['Bedroom', 'Master Bedroom'],
    deviceClass: 'blinds',
    icon: '/icons/blinds.svg',
    capabilities: ['windowcoverings_set'],
    initialState: { windowcoverings_set: 0.35 },
  },
  {
    id: 'living-room-speaker',
    name: 'Living room speaker',
    zoneCandidates: ['Living Room'],
    deviceClass: 'speaker',
    icon: '/icons/speaker.svg',
    capabilities: ['speaker_playing', 'volume_set', 'volume_mute'],
    initialState: { speaker_playing: false, volume_set: 0.32, volume_mute: false },
  },
];
