name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npm run build
      - name: Prepare release package
        run: |
          mkdir temp_release
          cp -r custom_components temp_release/
          mkdir -p temp_release/www/navet_ru/
          cp -r dist/* temp_release/www/navet_ru/
          cd temp_release
          zip -r ../navet.zip .
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: navet.zip
          generate_release_notes: true